"""
配置包初始化文件
"""

from .combined_config import (
    MODEL_NAME, TEMPERATURE, MAX_TOKENS,
    OPENAI_API_KEY, ANTHROPIC_API_KEY, MAGIC_TOWER_API_KEY, DEEPSEEK_API_KEY,
    REQUEST_TIMEOUT, MAX_RETRIES,
    GPT4_CONFIG,
    API_BASE_URL,
    MAGIC_TOWER_API_CONFIG,
    LOCAL_API_CONFIG,
    API_CLIENT_CONFIG,
    API_ENDPOINTS
)